yaml
name: Python Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: GitHubのコードを取得
        uses: actions/checkout@v4

      - name: Pythonをセットアップ
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Pythonを実行
        run: python main.py
